.PHONY: all clean test

all:
	cd serialization && make all
	cd feedbus && make all

clean:
	cd serialization && make clean
	cd feedbus && make clean

test:
	cd serialization && make test
	cd feedbus && make test
	