.PHONY: all clean test

all:
	cd serialization && make all
	cd messages && make all

clean:
	cd serialization && make clean
	cd messages && make clean

test:
	cd serialization && make test
	cd messages && make test
	