.PHONY: all clean test

all:
	# cd io && make all
	# cd utils && make all
	cd feed-bus && make all

clean:
	# cd io && make clean
	# cd utils && make clean
	cd feed-bus && make clean

test:
	# cd io && make test
	# cd utils && make test
	cd feed-bus && make test
	