.PHONY: all clean install uninstall

all:
	cd clients && make all
	cd server && make all

install:
	cd clients && make install
	cd server && make install

uninstall:
	cd clients && make uninstall
	cd server && make uninstall

clean:
	cd clients && make clean
	cd server && make clean
